### ISSUE TITLE
Setup Access List

### ISSUE THREAD

**Issue by copatal8** [devopsproducts/products#106]
**As a member of the products team** ...
**I need to** setup Access List
**So that** we can set up our cloud

**Assumptions:**
* Professor will send details

**Acceptance Criteria:**
...

When Access List is set up, everyone on the team is invited and has access to deploy.
...

**Comment by copatal8** [comment]
Everyone should see an email invite to get access

**Comment by themp731** [comment]
I got an invite to join IBM cloud but haven't seen the access group. I will revisit soon
