### ISSUE TITLE
Translate Service

### ISSUE THREAD

**Issue by copatal8** [devopsproducts/products#35]
**As a member of the products team** ...
**I need to** build a service
**So that** we can perform product level actions

**Assumptions:**
* Service.py file, built along the same structure as service.py in lab-flask-tdd

**Acceptence Criteria:**
```
Performs all the services outlined below:

List Resources
Read a Resource
Create a Resource
Update a Resource
Delete a Resource
Query Resources by some attribute of the Resource
Perform some stateful Action on the Resource 
```

**Comment by themp731** [comment]
Adapting from Rofrano's lab-flask-tdd services.py file needs to be done

**Comment by themp731** [comment]
As a member of the products team we need to update the services.py file to properly handle the requests for our API service.

Acceptance Criteria:

All use cases are done
Previous Services.PY file is adapted from Rofrano's lab-flask-tdd file
