### ISSUE TITLE
Error 4:TestProductsServer.test_delete_product

### ISSUE THREAD

**Issue by copatal8** [devopsproducts/products#70]
**As a member of the products team** ...
**I need to** fix the errors in pytest
**So that** our code runs

**Assumptions:**
* Run pytest in vagrant

**Acceptence Criteria:**
...

Error no longer shows up
...

**Comment by copatal8** [comment]
self = <tests.test_server.TestProductsServer testMethod=test_delete_product>

    def test_delete_product(self):
        """ Delete a Product """
>       test_product = self._create_products(1)[0]
E       AttributeError: 'TestProductsServer' object has no attribute '_create_products'

tests/test_server.py:153: AttributeError

**Comment by MKraz110** [comment]
fixed attribution
