### ISSUE TITLE
Error 5:TestProductsServer.test_get_product

### ISSUE THREAD

**Issue by copatal8** [devopsproducts/products#71]
**As a member of the products team** ...
**I need to** fix the errors in pytest
**So that** our code runs

**Assumptions:**
* Run pytest in vagrant

**Acceptence Criteria:**
...

Error no longer shows up
...

**Comment by copatal8** [comment]
self = <tests.test_server.TestProductsServer testMethod=test_get_product>

    def test_get_product(self):
        """ Get a single Product """
        # get the id of a product
>       test_product = self._create_products(1)[0]
E       AttributeError: 'TestProductsServer' object has no attribute '_create_products'

tests/test_server.py:96: AttributeError

**Comment by MKraz110** [comment]
fixed attribution
