### ISSUE TITLE
Error 6: TestProductsServer.test_get_product_list

### ISSUE THREAD

**Issue by copatal8** [devopsproducts/products#72]
**As a member of the products team** ...
**I need to** fix the errors in pytest
**So that** our code runs

**Assumptions:**
* Run pytest in vagrant

**Acceptence Criteria:**
...

Error no longer shows up
...

**Comment by copatal8** [comment]
self = <tests.test_server.TestProductsServer testMethod=test_get_product_list>

    def test_get_product_list(self):
        """ Get a list of Products """
>       self._create_products(5)
E       AttributeError: 'TestProductsServer' object has no attribute '_create_products'

tests/test_server.py:87: AttributeError

**Comment by MKraz110** [comment]
fixed attribution
