### ISSUE TITLE
Error 7: TestProductsServer.test_query_product_list_by_category

### ISSUE THREAD

**Issue by copatal8** [devopsproducts/products#73]
**As a member of the products team** ...
**I need to** fix the errors in pytest
**So that** our code runs

**Assumptions:**
* Run pytest in vagrant

**Acceptance Criteria:**
...

Error no longer shows up
...

**Comment by copatal8** [comment]
self = <tests.test_server.TestProductsServer testMethod=test_query_product_list_by_category>

    def test_query_product_list_by_category(self):
        """ Query Proucts by Category """
>       products = self._create_products(10)
E       AttributeError: 'TestProductsServer' object has no attribute '_create_products'

tests/test_server.py:165: AttributeError

**Comment by MKraz110** [comment]
fixed attribution
