### ISSUE TITLE
Team Members Create Travis CI Free Account

### ISSUE THREAD

**Issue by themp731** [devopsproducts/products#90]
Each team member needs to have a Travis CI account and make sure that our Travis CI is linked to the Repo

Acceptance Criteria:
Each member has a Travis CI account, we can see our Products Repo within the dashboard

**Comment by themp731** [comment]
@sg5717 @copatal8 @MKraz110 Make sure you comment here when you've got Travis CI set up

**Comment by sg5717** [comment]
i have done this for my account

**Comment by themp731** [comment]
Thanks!

-Matt Markezin-Press
 (Sent from my mobile device)
